# 配置文件加密key
jasypt:
  encryptor:
    password: music

server:
  port: 8888
  servlet:
    context-path: /music


spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/music?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
   # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
   # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

music:
  # token过期时间（分钟）
  tokenExpireTime: 30
  # 用户选择保存登录状态对应token过期时间（天）
#  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
#  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
#  loginAfterTime: 10
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false

# 忽略鉴权url
ignored:
  urls:
    - /api/permission/getMenuList/**
    - /api/user/regist
    - /api/common/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

# Swagger界面内容配置
swagger:
  title: Music-API接口文档
  description: Api Documentation
  version: 1.0.0
  termsOfServiceUrl:
  contact:
    name:
    url:
    email:

mqtt:
    username: admin
    password: public
    host: tcp://localhost:1883
    clientId: mqttjs_420e553e39
    topic: test
    timeout: 1000
    keepAlive: 2000

